name: Build Docker Image

on:
    push:
        paths:
            - "headless/**"
    pull_request:
        paths:
            - "headless/**"

jobs:
    ci:
        runs-on: ubuntu-latest
        name: CI - build headless image
        steps:
            -
                name: checkout code
                uses: actions/checkout@v2
            -
                name: install buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    buildx-version: latest
            -
                name: build headless image
                run: |
                    docker buildx build \
                    --no-cache \
                    --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 headless/
