name: CD - build and deploy traditional image

on:
    push:
        branches:
            - master
        paths:
            - "traditional/**"

env:
    IMAGE_OWNER: soapmedia
    IMAGE_NAME: standard
    IMAGE_VERSION: 0.1

jobs:
    cd-traditional-ubuntu:
        env:
            IMAGE_TYPE: traditional
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout Code
                uses: actions/checkout@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            -
                name: Install Buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    buildx-version: latest
            -
                name: Build and Push
                run: |
                    docker buildx build \
                        --push \
                        --no-cache \
                        --tag ${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}-${{ env.IMAGE_TYPE }} \
                        --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 \
                        traditional/ubuntu/

    cd-traditional-alpine:
        env:
            IMAGE_TYPE: traditional-alpine
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout Code
                uses: actions/checkout@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            -
                name: Install Buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    buildx-version: latest
            -
                name: Build and Push
                run: |
                    docker buildx build \
                        --push \
                        --no-cache \
                        --tag ${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}-${{ env.IMAGE_TYPE }} \
                        --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 \
                        traditional/alpine/
