name: CI - build headless image

on:
    push:
        branches-ignore:
            - master
        paths:
            - "headless/**"
            - ".github/**"
    pull_request:
        paths:
            - "headless/**"
            - ".github/**"

jobs:
    ci-headless:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout Code
                uses: actions/checkout@v3
            -
                name: Install Buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    buildx-version: latest
            -
                name: Build Image
                run: |
                    docker buildx build \
                    --no-cache \
                    --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 headless/
